### ISSUE TITLE
Decide elm code file structure

### ISSUE THREAD

**Issue by sonowz** [sonowz/graduate-adventure#12]
There are 2 major file structures suggested for elm codes. [Reference](https://medium.com/@_rchaves_/structured-todomvc-example-with-elm-a68d87cd38da#.l6c9zqs9r)

### Concerns-focused structure
- Create directories by `functions` (Model, Msg, Update, View),
- Then files by `modules`. (TextBox, Combobox, Graph..)

### Modules-focused structure
- Create directories by `modules`,
- Then files by `functions`.

This is a minor issue, but deciding the structure affects code maintenance, and **elegance**.

**Comment by dj-shin** [comment]
I prefer modules-focused structure, for it will be better to understand or lookup components.

**Comment by dj-shin** [comment]
@skystar-p @Jhuni0123 Any opinions?

**Comment by Jhuni0123** [comment]
Modules-focused structure would be better.

**Comment by skystar-p** [comment]
Modules-focused structure **must** be more better in terms of handy browsing.

**Comment by sonowz** [comment]
Then I will make file structure as module-focused structure.
