### ISSUE TITLE
Rule schema

### ISSUE THREAD

**Issue by dj-shin** [sonowz/graduate-adventure#4]
### Design
Tree-based rule model

### Implementation
 - [x] Implementing schema using [YAML](http://yaml.org/)
 - [x] Sample rule data for CSE major
 - [x] Add tests

**Comment by skystar-p** [comment]
PyYAML Documentation : [http://pyyaml.org/wiki/PyYAMLDocumentation](http://pyyaml.org/wiki/PyYAMLDocumentation)
