### ISSUE TITLE
Frontend environment setting

### ISSUE THREAD

**Issue by sonowz** [sonowz/graduate-adventure#98]
- [x] CI
- [x] eslint
- [x] .gitignore
- [x] package.json
- [x] README.md

**Comment by Jhuni0123** [comment]
We will use `vue.js` with `Nuxt.js`. We can easily start with this [Nuxt.js installation guide](https://ko.nuxtjs.org/guide/installation#처음부터-시작하기)

**Comment by sonowz** [comment]
Understood.
